tabWidth: 2
useTabs: false
printWidth: 88 # Like Python's Black
singleQuote: true
trailingComma: all
plugins: ['@ianvs/prettier-plugin-sort-imports']
importOrder: ['<BUILTIN_MODULES>', '', '<THIRD_PARTY_MODULES>', '', '^[.]']
